FROM chrislusf/seaweedfs:latest

USER root

# Install AWS CLI
RUN apk add --no-cache aws-cli

RUN mkdir -p /data1 && chmod -R 777 /data1

COPY ./hacks/setup.sh /usr/bin/setup.sh
COPY ./hacks/start.sh /usr/bin/start.sh

RUN chmod +x /usr/bin/setup.sh
RUN chmod +x /usr/bin/start.sh

# Set working directory to /data1 so filer uses /data1/filerldb2
WORKDIR /data1

EXPOSE 8333 9333 8888 9340 23646

# Switch to the new user
USER 1000
ENTRYPOINT ["/usr/bin/start.sh"]
