apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_S3_BUCKET: ZXhhbXBsZS1tb2RlbHM=
  AWS_S3_ENDPOINT: aHR0cDovL21pbmlvLm1pbmlvLnN2Yzo5MDAw
  AWS_SECRET_ACCESS_KEY: cGFzc3dvcmQ=
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: minio
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  name: aws-connection-minio
type: Opaque
