apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  clusterIP: 10.96.223.25
  clusterIPs:
  - 10.96.223.25
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: master-ui
    port: 9333
    protocol: TCP
    targetPort: 9333
  - name: filer-ui
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: s3
    port: 8333
    protocol: TCP
    targetPort: 8333
  - name: volume
    port: 9340
    protocol: TCP
    targetPort: 9340
  - name: admin-ui
    port: 23646
    protocol: TCP
    targetPort: 23646
  selector:
    app: seaweedfs
  sessionAffinity: None
  type: ClusterIP
